/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddCourseDto } from './models/AddCourseDto';
export type { AddStudentDto } from './models/AddStudentDto';
export type { AddTeacherDto } from './models/AddTeacherDto';
export { AdminUpdateUserDto } from './models/AdminUpdateUserDto';
export type { AnswerDto } from './models/AnswerDto';
export type { AnswerEntiti } from './models/AnswerEntiti';
export type { AppConfigEntity } from './models/AppConfigEntity';
export type { BlogEntity } from './models/BlogEntity';
export type { ClassDetailEntity } from './models/ClassDetailEntity';
export type { ClassDetailOfStudentEntity } from './models/ClassDetailOfStudentEntity';
export type { ClassEntity } from './models/ClassEntity';
export type { ClassExamResultDetailEntity } from './models/ClassExamResultDetailEntity';
export type { ClassExamResultEntity } from './models/ClassExamResultEntity';
export type { ClassReviewEntity } from './models/ClassReviewEntity';
export type { ClassStudentDetailEntity } from './models/ClassStudentDetailEntity';
export type { CloneScheduleDto } from './models/CloneScheduleDto';
export type { CommentPostEntity } from './models/CommentPostEntity';
export type { ConfirmRegisterDto } from './models/ConfirmRegisterDto';
export type { CourseDetailOfStudentEntity } from './models/CourseDetailOfStudentEntity';
export { CourseEntity } from './models/CourseEntity';
export type { CourseVocabEntity } from './models/CourseVocabEntity';
export type { CreateClassDto } from './models/CreateClassDto';
export type { CreateClassReviewDto } from './models/CreateClassReviewDto';
export type { CreateClassSessonScheduleDto } from './models/CreateClassSessonScheduleDto';
export type { CreateCommentDto } from './models/CreateCommentDto';
export { CreateCourseDto } from './models/CreateCourseDto';
export type { CreateCourseVocabDto } from './models/CreateCourseVocabDto';
export type { CreateDocumentType } from './models/CreateDocumentType';
export type { CreateEssayTestDto } from './models/CreateEssayTestDto';
export type { CreateExamAndAddToLessonDto } from './models/CreateExamAndAddToLessonDto';
export type { CreateExamDto } from './models/CreateExamDto';
export type { CreateExamLessonDto } from './models/CreateExamLessonDto';
export type { CreateFlashCardDto } from './models/CreateFlashCardDto';
export type { CreateGrammarDto } from './models/CreateGrammarDto';
export type { CreateKanjiDto } from './models/CreateKanjiDto';
export type { CreateLessonCommentDto } from './models/CreateLessonCommentDto';
export { CreateLessonDto } from './models/CreateLessonDto';
export type { CreateNotificationTokenDto } from './models/CreateNotificationTokenDto';
export type { CreatePostDto } from './models/CreatePostDto';
export type { CreatePostTagDto } from './models/CreatePostTagDto';
export { CreateQuestionDto } from './models/CreateQuestionDto';
export type { CreateQuestionFlashCardDto } from './models/CreateQuestionFlashCardDto';
export { CreateQuestionGroupAndReferenceDto } from './models/CreateQuestionGroupAndReferenceDto';
export type { CreateQuestionGroupDto } from './models/CreateQuestionGroupDto';
export { CreateQuestionGroupReferenceDto } from './models/CreateQuestionGroupReferenceDto';
export type { CreateQuizFlashCardDto } from './models/CreateQuizFlashCardDto';
export type { CreateSessonDto } from './models/CreateSessonDto';
export type { CreateSlideDto } from './models/CreateSlideDto';
export { CreateTestCategoryDto } from './models/CreateTestCategoryDto';
export type { CreateTestDetailDto } from './models/CreateTestDetailDto';
export { CreateTestDto } from './models/CreateTestDto';
export type { CreateTestProgressDto } from './models/CreateTestProgressDto';
export type { CreateTestResultDto } from './models/CreateTestResultDto';
export type { CreateTextDto } from './models/CreateTextDto';
export type { CreateTopicDto } from './models/CreateTopicDto';
export type { CreateTopicVocabDto } from './models/CreateTopicVocabDto';
export type { CreateVideoUrlDto } from './models/CreateVideoUrlDto';
export type { DeleteDocumentType } from './models/DeleteDocumentType';
export type { DocumentEntityType } from './models/DocumentEntityType';
export type { DropDownAnswerDto } from './models/DropDownAnswerDto';
export { DropDownUserAnswerDto } from './models/DropDownUserAnswerDto';
export type { EncryptedResponse } from './models/EncryptedResponse';
export { EnrolledCourseEntity } from './models/EnrolledCourseEntity';
export type { EssayAnswerDto } from './models/EssayAnswerDto';
export type { EssayAnswerEntity } from './models/EssayAnswerEntity';
export type { EssayTestEntity } from './models/EssayTestEntity';
export type { ExamEntity } from './models/ExamEntity';
export type { ExamLessonEntity } from './models/ExamLessonEntity';
export type { ExamLessonWithMappingEntity } from './models/ExamLessonWithMappingEntity';
export type { ExamResulEntity } from './models/ExamResulEntity';
export type { ExamResulHistoryDetailEntity } from './models/ExamResulHistoryDetailEntity';
export type { ExamResulHistoryEntity } from './models/ExamResulHistoryEntity';
export type { ExamResultInCourseOfStudentEntity } from './models/ExamResultInCourseOfStudentEntity';
export type { ExamResultWithExamEntity } from './models/ExamResultWithExamEntity';
export type { ExamWithMappingEntity } from './models/ExamWithMappingEntity';
export type { FlashCardEntity } from './models/FlashCardEntity';
export type { FlashCardStatusEntity } from './models/FlashCardStatusEntity';
export type { ForgotPasswordInputDto } from './models/ForgotPasswordInputDto';
export type { ForumRankingEntity } from './models/ForumRankingEntity';
export type { ForumRankingUserEntity } from './models/ForumRankingUserEntity';
export type { GrammarEntity } from './models/GrammarEntity';
export type { GroupedTestDetailEntity } from './models/GroupedTestDetailEntity';
export { HandWritingDto } from './models/HandWritingDto';
export type {
  HandWritingAnswerPayload,
  HandWritingUserAnswerDto,
} from './models/HandWritingUserAnswerDto';
export type { IBaseResponse } from './models/IBaseResponse';
export type { IContextUser } from './models/IContextUser';
export type { ILoginResponse } from './models/ILoginResponse';
export type { IMessageResponse } from './models/IMessageResponse';
export type { IMeta } from './models/IMeta';
export type { InBlankAnswerDto } from './models/InBlankAnswerDto';
export { InBlankUserAnswerDto } from './models/InBlankUserAnswerDto';
export type { InformationEssayTestEntity } from './models/InformationEssayTestEntity';
export type { IPaginatedResponse } from './models/IPaginatedResponse';
export type { JoinTestDto } from './models/JoinTestDto';
export type { KanjiDictionaryEntity } from './models/KanjiDictionaryEntity';
export type { KanjiEntity } from './models/KanjiEntity';
export type { LessonCommentEntity } from './models/LessonCommentEntity';
export { LessonEntity } from './models/LessonEntity';
export type { LessonProgressEntity } from './models/LessonProgressEntity';
export { LessonStudentEntity } from './models/LessonStudentEntity';
export type { LoginAppleDto } from './models/LoginAppleDto';
export type { LoginFacebookDto } from './models/LoginFacebookDto';
export type { LoginGoogleDto } from './models/LoginGoogleDto';
export { LoginInputDto } from './models/LoginInputDto';
export type { LoginLineDto } from './models/LoginLineDto';
export type { ManagerHasSubmittedEntity } from './models/ManagerHasSubmittedEntity';
export type { MatchingAnswerDto } from './models/MatchingAnswerDto';
export { MatchingUserAnswerDto } from './models/MatchingUserAnswerDto';
export type { MessageEvent } from './models/MessageEvent';
export type { MultipleChoiceAnswerDto } from './models/MultipleChoiceAnswerDto';
export type { MultipleChoiceHorizontalDto } from './models/MultipleChoiceHorizontalDto';
export { MultipleChoiceHorizontalUserAnswerDto } from './models/MultipleChoiceHorizontalUserAnswerDto';
export { MultipleChoiceUserAnswerDto } from './models/MultipleChoiceUserAnswerDto';
export type { NoContentResponse } from './models/NoContentResponse';
export { NotificationEntity } from './models/NotificationEntity';
export { NotificationTokenEntity } from './models/NotificationTokenEntity';
export type { Number } from './models/Number';
export type { ObjectId } from './models/ObjectId';
export { PostEntity } from './models/PostEntity';
export type { PostTagEntity } from './models/PostTagEntity';
export type { PostTagRankingEntity } from './models/PostTagRankingEntity';
export { QuestionEntity } from './models/QuestionEntity';
export type { QuestionFlashCardEntity } from './models/QuestionFlashCardEntity';
export type { QuestionGroupEntity } from './models/QuestionGroupEntity';
export { QuestionGroupReferenceEntity } from './models/QuestionGroupReferenceEntity';
export type { QuestionGroupUserAnswerEntity } from './models/QuestionGroupUserAnswerEntity';
export type { QuestionUserAnswerEntity } from './models/QuestionUserAnswerEntity';
export type { QuizFlashCardEntity } from './models/QuizFlashCardEntity';
export type { RefreshTokenInputDto } from './models/RefreshTokenInputDto';
export type { RegisterInputDto } from './models/RegisterInputDto';
export { ResendCodeInputDto } from './models/ResendCodeInputDto';
export type { ResetPasswordInputDto } from './models/ResetPasswordInputDto';
export type { SaveTemporaryAnswerDto } from './models/SaveTemporaryAnswerDto';
export type { SessonEntity } from './models/SessonEntity';
export type { SessonProgressOfStudentEntity } from './models/SessonProgressOfStudentEntity';
export type { SessonScheduleEntity } from './models/SessonScheduleEntity';
export type { SessonScheduleLessonEntity } from './models/SessonScheduleLessonEntity';
export type { SessonScheduleSessonEntity } from './models/SessonScheduleSessonEntity';
export type { SessonScheduleStatusEntity } from './models/SessonScheduleStatusEntity';
export type { SessonScheduleWithLessonEntity } from './models/SessonScheduleWithLessonEntity';
export type { SessonStudentEntity } from './models/SessonStudentEntity';
export type { SlideEntity } from './models/SlideEntity';
export type { SortingAnswerDto } from './models/SortingAnswerDto';
export { SortingUserAnswerDto } from './models/SortingUserAnswerDto';
export type { StudentDetailEntity } from './models/StudentDetailEntity';
export type { SwitchTestDetailDto } from './models/SwitchTestDetailDto';
export type { TemporaryAnswerType } from './models/TemporaryAnswerType';
export { TestCategoryEntity } from './models/TestCategoryEntity';
export type { TestDetailEntity } from './models/TestDetailEntity';
export { TestDetailGroupEntity } from './models/TestDetailGroupEntity';
export type { TestDetailWithoutTestEntity } from './models/TestDetailWithoutTestEntity';
export { TestEntity } from './models/TestEntity';
export type { TestProcessDetailEntity } from './models/TestProcessDetailEntity';
export type { TestProgressEntity } from './models/TestProgressEntity';
export type { TestResultAdminAttemptCountEntity } from './models/TestResultAdminAttemptCountEntity';
export type { TestResultAdminEntity } from './models/TestResultAdminEntity';
export type { TestResultAdminSummaryEntity } from './models/TestResultAdminSummaryEntity';
export type { TestResultEntity } from './models/TestResultEntity';
export type { TestResultUserDetailEntity } from './models/TestResultUserDetailEntity';
export type { TestResultUserDetailGroupEntity } from './models/TestResultUserDetailGroupEntity';
export type { TestResultUserDetailWithoutTestEntity } from './models/TestResultUserDetailWithoutTestEntity';
export type { TextEntity } from './models/TextEntity';
export { ToggleReactionDto } from './models/ToggleReactionDto';
export type { TopicEntity } from './models/TopicEntity';
export type { TopicVocabEntity } from './models/TopicVocabEntity';
export type { UpdateClassDto } from './models/UpdateClassDto';
export type { UpdateClassReviewDto } from './models/UpdateClassReviewDto';
export type { UpdateCommentDto } from './models/UpdateCommentDto';
export { UpdateCourseDto } from './models/UpdateCourseDto';
export type { UpdateCourseVocabDto } from './models/UpdateCourseVocabDto';
export type { UpdateDocumentType } from './models/UpdateDocumentType';
export type { UpdateEssayTestDto } from './models/UpdateEssayTestDto';
export type { UpdateExamDto } from './models/UpdateExamDto';
export type { UpdateExamLessonDto } from './models/UpdateExamLessonDto';
export type { UpdateFlashCardDto } from './models/UpdateFlashCardDto';
export type { UpdateGrammarDto } from './models/UpdateGrammarDto';
export type { UpdateKanjiDto } from './models/UpdateKanjiDto';
export type { UpdateLessonCommentDto } from './models/UpdateLessonCommentDto';
export type { UpdateLessonDto } from './models/UpdateLessonDto';
export type { UpdateLessonsSessonSchedulesDto } from './models/UpdateLessonsSessonSchedulesDto';
export { UpdateLocaleDto } from './models/UpdateLocaleDto';
export type { UpdateLoginProviderDto } from './models/UpdateLoginProviderDto';
export type { UpdateNotificationDto } from './models/UpdateNotificationDto';
export type { UpdatePostDto } from './models/UpdatePostDto';
export type { UpdatePostTagDto } from './models/UpdatePostTagDto';
export { UpdateQuestionDto } from './models/UpdateQuestionDto';
export type { UpdateQuestionFlashCardDto } from './models/UpdateQuestionFlashCardDto';
export type { UpdateQuestionGroupDto } from './models/UpdateQuestionGroupDto';
export type { UpdateQuizFlashCardDto } from './models/UpdateQuizFlashCardDto';
export type { UpdateSessonDto } from './models/UpdateSessonDto';
export type { UpdateSlideDto } from './models/UpdateSlideDto';
export type { UpdateSubmitEssayUserDto } from './models/UpdateSubmitEssayUserDto';
export type { UpdateTagMultipleQuestionDto } from './models/UpdateTagMultipleQuestionDto';
export { UpdateTestCategoryDto } from './models/UpdateTestCategoryDto';
export type { UpdateTestDetailDto } from './models/UpdateTestDetailDto';
export { UpdateTestDto } from './models/UpdateTestDto';
export type { UpdateTestProgressDto } from './models/UpdateTestProgressDto';
export type { UpdateTestResultDto } from './models/UpdateTestResultDto';
export type { UpdateTextDto } from './models/UpdateTextDto';
export type { UpdateTopicDto } from './models/UpdateTopicDto';
export type { UpdateTopicVocabDto } from './models/UpdateTopicVocabDto';
export { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateUserPasswordDto } from './models/UpdateUserPasswordDto';
export type { UpdateUserStatusDto } from './models/UpdateUserStatusDto';
export type { UpdateVideoUrlDto } from './models/UpdateVideoUrlDto';
export type { UpsertExamResultStudentDto } from './models/UpsertExamResultStudentDto';
export type { UpsertLessonProgressDto } from './models/UpsertLessonProgressDto';
export { UpsertUserDto } from './models/UpsertUserDto';
export type { UserAnswerEntity } from './models/UserAnswerEntity';
export { UserBaseEntity } from './models/UserBaseEntity';
export { UserEntity } from './models/UserEntity';
export { VerifyCodeInputDto } from './models/VerifyCodeInputDto';
export type { VideoUrlEntity } from './models/VideoUrlEntity';

export { AppService } from './services/AppService';
export { AuthService } from './services/AuthService';
export { ClassReviewService } from './services/ClassReviewService';
export { ClassService } from './services/ClassService';
export { ConfigsService } from './services/ConfigsService';
export { CourseService } from './services/CourseService';
export { CourseVocabService } from './services/CourseVocabService';
export { EssayTestService } from './services/EssayTestService';
export { ExamLessonService } from './services/ExamLessonService';
export { ExamResultService } from './services/ExamResultService';
export { ExamService } from './services/ExamService';
export { FlashCardService } from './services/FlashCardService';
export { GrammarService } from './services/GrammarService';
export { KanjiDictionaryService } from './services/KanjiDictionaryService';
export { KanjiService } from './services/KanjiService';
export { LessonCommentService } from './services/LessonCommentService';
export { LessonProgressService } from './services/LessonProgressService';
export { LessonService } from './services/LessonService';
export { NotificationsService } from './services/NotificationsService';
export { NotificationTokensService } from './services/NotificationTokensService';
export { PostCommentService } from './services/PostCommentService';
export { PostService } from './services/PostService';
export { PostTagService } from './services/PostTagService';
export { QuestionFlashCardService } from './services/QuestionFlashCardService';
export { QuestionGroupService } from './services/QuestionGroupService';
export { QuestionGroupsReferencesService } from './services/QuestionGroupsReferencesService';
export { QuestionService } from './services/QuestionService';
export { QuizFlashCardService } from './services/QuizFlashCardService';
export { RankingService } from './services/RankingService';
export { SessonScheduleService } from './services/SessonScheduleService';
export { SessonService } from './services/SessonService';
export { SlideService } from './services/SlideService';
export { TestCategoryService } from './services/TestCategoryService';
export { TestDetailService } from './services/TestDetailService';
export { TestProgressService } from './services/TestProgressService';
export { TestResultService } from './services/TestResultService';
export { TestService } from './services/TestService';
export { TextService } from './services/TextService';
export { TopicService } from './services/TopicService';
export { TopicVocabService } from './services/TopicVocabService';
export { UploadS3Service } from './services/UploadS3Service';
export { UsersService } from './services/UsersService';
export { VideoUrlService } from './services/VideoUrlService';
